:sparkles: Add Delivery Note, Purchase Order, Request for Quotation, …
Monogramm/recod_erpnext_design pull request #6
Opened 2020-08-12 12:58 UTC by AminovE99

…Sales Order Print Formats for new Doctypes.

> Please provide enough information so that others can review your pull request:

> Explain the **details** for making this change. What existing problem does the pull request solve?

> Screenshots/GIFs
![recod_print_format_delivery_note](https://user-images.githubusercontent.com/32329685/90017634-7eee6c80-dcb4-11ea-81ca-96e6a9dc1aa2.png)
![recod_print_format_request_for_quotation](https://user-images.githubusercontent.com/32329685/90017635-801f9980-dcb4-11ea-8560-83f2deaa09c8.png)
![recod_print_format_purchase_order](https://user-images.githubusercontent.com/32329685/90017638-80b83000-dcb4-11ea-86cc-9a1bc9c0fe09.png)
![recod_print_format_sales_order](https://user-images.githubusercontent.com/32329685/90017640-80b83000-dcb4-11ea-8c3f-6aa0b5a942a5.png)

2020-08-13 14:40 UTC, madmath03 requested changes

2020-08-13 14:40 UTC, madmath03 commented on recod_erpnext_design/fixtures/print_format.json
> +  "module": "Stock",
Wrong module.
```suggestion
  "module": "Recod ERPNext Design",
```

2020-08-13 14:40 UTC, madmath03 commented on recod_erpnext_design/fixtures/print_format.json
> +  "module": "Buying",
Wrong module.
```suggestion
  "module": "Recod ERPNext Design",
```

2020-08-13 14:40 UTC, madmath03 commented on recod_erpnext_design/fixtures/print_format.json
> +  "module": "Buying",
Wrong module.
```suggestion
  "module": "Recod ERPNext Design",
```

2020-08-13 14:40 UTC, madmath03 commented on recod_erpnext_design/fixtures/print_format.json
> +  "module": "Selling",
Wrong module.
```suggestion
  "module": "Recod ERPNext Design",
```

2020-08-23 15:56 UTC, rai-monogramm commented
Ok, you can implement them

2020-08-23 15:59 UTC, madmath03 approved these changes

2020-08-24 00:15 UTC, merged